export const nameBand = 'MAC DEMARCO';
export const nameSongs = [
	"HERE COMES THE COWBOY", /*1*/
	"NOBODY", /*2*/
	"CHAMBER OF REFLECTION", /*3*/
	"PASSING OUT PIECES", /*4*/
	"ALL OF OUR YESTERDAYS", /*5*/
	"ON THE SQUARE", /*6*/
	"WONDERFUL CHRISTMAS TIME", /*7*/
	"PIANO TIME", /*8*/
	"HAVE YOURSELF A MERRY LITTLE CHRISTMAS", /*9*/
	"WHITE CHRISTMAS", /*10*/
	"I'LL BE HOME FOR CHRISTMAS", /*11*/
	"SIMPLY PARADISE", /*12*/
	"SANTA CLAUS IS COMING TO TOWN", /*13*/
	"ME & MINE", /*14*/
	"JOE BUCK", /*15*/
	"RED CARPET 7 INCH", /*16*/
	"PICKLES", /*17*/
	"STILL WHAT I'M LOOKING FOR", /*18*/
	"TOGETHER", /*19*/
	"HE MY BROTHER", /*20*/
]